### PR TITLE
Python 3.2 -> 3.4 are EOL

### PR DESCRIPTION
**Pull request by sharoonthomas**
Remove them from CI

### CODE REVIEW

**Comment by sir-sigurd** [comment]
Might make sense to update trove classifiers as well:
https://github.com/vcatalano/py-authorize/blob/4c6c9a114914886fcf38376b7ea6f78e11cc3173/setup.py#L25-L30

**Comment by sharoonthomas** [comment]
Is travis not running anymore on PRs?

**Comment by vcatalano** [comment]
> Is travis not running anymore on PRs?

Hmmm, it should be... I'm not sure why it didn't run here. I will take a look.

**Comment by vcatalano** [comment]
Thank you for your contribution to this project!

**Pull request merged**
