### PR TITLE
Handle Opaque Data for payment

### PR DESCRIPTION
**Pull request by glassfordm**
Necessary for sites wanting to implement this http://developer.authorize.net/api/reference/features/acceptjs.html

### CODE REVIEW

**Comment by rdavidso** [comment]
Are there any updates on when this will be merged into master?

**Comment by glassfordm** [comment]
I don't think any updates are needed. The checks that failed are only the ones for Python 3.2, and that's because your version of nose is reporting that one of its plugins requires Python 3.3 or greater--nothing to do with the pull request.

**Comment by rdavidso** [comment]
Does this mean I should just use your `glassfordm:feature/opaque_data` branch then?

**Comment by glassfordm** [comment]
That's what it means, yes. Thanks!

**Comment by sharoonthomas** [comment]
Would be great to have this merged into the repo. @vcatalano do you need help in maintaining?

**Comment by vcatalano** [comment]
> Would be great to have this merged into the repo. @vcatalano do you need help in maintaining?

Hello @sharoonthomas , I am finally getting back to this project after a while. If you are still willing to help as a maintainer, that would be great!

**Comment by sharoonthomas** [comment]
> > Would be great to have this merged into the repo. @vcatalano do you need help in maintaining?
> 
> Hello @sharoonthomas , I am finally getting back to this project after a while. If you are still willing to help as a maintainer, that would be great!

Great to have you back and Happy to help Vincent.

**Comment by vcatalano** [comment]
It looks like Python 3.2 is EoL, should 3.2 be removed from the integration tests?

**Comment by robertpro** [comment]
Is this something that will be implemented? Looks like with this we'll be able to use Google Pay.

**Pull request merged**
